version: '3'
services:
  database:
    image: "mongo:latest"

    networks:
      local:
        aliases:
          - database

  server:
    build: "./docker/server"
    working_dir: /app
    volumes:
      - "./:/app"

    ports:
      - "8085:8085"
      - "3000:3000"

    entrypoint: bash -c "yarn && yarn dev"
    tty: true

  tests:
    build: "./docker/tests"
    working_dir: /app
    volumes:
      - "./:/app"
    entrypoint: bash -c "yarn && yarn test"
    tty: true

networks:
  local: