version: '3'
services:
  database:
    image: "mongo:latest"

    ports:
      - "27017:27017"

    logging:
      driver: "none"

    networks:
      local:
        aliases:
          - database

  server:
    build: "./docker/server"
    working_dir: /app
    volumes:
      - "./:/app"

    ports:
      - "8085:8085"
      - "3000:3000"

    entrypoint: bash -c "yarn && yarn dev"
    tty: true

    environment:
      - NODE_ENV=docker

    depends_on:
      - "database"

    networks:
      local:
        aliases:
          - server
  tests:
    build: "./docker/tests"
    working_dir: /app
    volumes:
      - "./:/app"
    entrypoint: bash -c "yarn && yarn test"
    tty: true
    depends_on:
      - "database"
      - "server"

    environment:
      - NODE_ENV=dockerTests

    networks:
      local:
        aliases:
          - tests
networks:
  local: